# Generated by Django 2.0.4 on 2018-04-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='sid',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
