# Generated by Django 2.0.4 on 2018-04-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_register_sid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='roll',
            new_name='studid',
        ),
    ]
