# Generated by Django 2.0.4 on 2018-05-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_logs_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='sid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
