# Generated by Django 2.0.4 on 2018-05-02 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_logs_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('logid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Logs')),
            ],
        ),
    ]
