# Generated by Django 2.0.4 on 2018-05-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='status',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
