# Generated by Django 2.0.4 on 2018-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20180503_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
