# Generated by Django 2.0.4 on 2018-05-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20180503_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=1)),
                ('questid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Quest')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Logs')),
            ],
        ),
    ]
