# Generated by Django 2.0.4 on 2018-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20180503_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='questid',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
