# Generated by Django 2.0.4 on 2018-05-04 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_ans_questid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='questid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Quest'),
        ),
    ]
