# Generated by Django 2.0.4 on 2018-05-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20180504_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
