# Generated by Django 2.0.4 on 2018-05-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='questid',
            field=models.CharField(max_length=100),
        ),
    ]
