# Generated by Django 2.0.4 on 2018-05-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20180506_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='logid',
            field=models.CharField(max_length=500),
        ),
    ]
