# Generated by Django 2.0.5 on 2018-05-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20180507_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ans',
            name='users',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
