# Generated by Django 2.0.5 on 2018-05-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_ans_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='comm',
            name='users',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
