# Generated by Django 2.0.5 on 2018-05-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_comm_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='users',
            field=models.CharField(default='unknwn', max_length=100),
        ),
        migrations.AlterField(
            model_name='ans',
            name='users',
            field=models.CharField(default='unknwn', max_length=100),
        ),
        migrations.AlterField(
            model_name='comm',
            name='users',
            field=models.CharField(default='unknwn', max_length=100),
        ),
    ]
