# Generated by Django 2.0.5 on 2018-05-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_auto_20180508_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ans',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
